// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIAHuqv_d3uRlOK7BsMIGgHW0DOYKvoBA',
    appId: '1:471504723896:web:66cf83a2adb600fa7cb94d',
    messagingSenderId: '471504723896',
    projectId: 'mukjang-12e08',
    authDomain: 'mukjang-12e08.firebaseapp.com',
    storageBucket: 'mukjang-12e08.appspot.com',
    measurementId: 'G-KWC42EY8ZK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAydF38pRX53fmQf9i_hVlLVB2F8jLjP70',
    appId: '1:471504723896:android:16e492afd3b623577cb94d',
    messagingSenderId: '471504723896',
    projectId: 'mukjang-12e08',
    storageBucket: 'mukjang-12e08.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx6KsaDnJKM9p_c6psdWiLaKOlbXuEhfo',
    appId: '1:471504723896:ios:d85b24ae57191c8f7cb94d',
    messagingSenderId: '471504723896',
    projectId: 'mukjang-12e08',
    storageBucket: 'mukjang-12e08.appspot.com',
    iosClientId: '471504723896-9g3p04aour98u39103e4vb02stgcdoas.apps.googleusercontent.com',
    iosBundleId: 'com.example.brainstormMeokjang',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDx6KsaDnJKM9p_c6psdWiLaKOlbXuEhfo',
    appId: '1:471504723896:ios:d85b24ae57191c8f7cb94d',
    messagingSenderId: '471504723896',
    projectId: 'mukjang-12e08',
    storageBucket: 'mukjang-12e08.appspot.com',
    iosClientId: '471504723896-9g3p04aour98u39103e4vb02stgcdoas.apps.googleusercontent.com',
    iosBundleId: 'com.example.brainstormMeokjang',
  );
}
